name: "e2g-setup-calculator-action"
description: "Internal use"
author: "Equity Engineering Group"
outputs:
  releaseEnv:
    description: The environment name for the releaseEnv
  serviceName:
    description: The name of the service in the kubernetes manifests
  imageName:
    description: The name of the image in the container registry
  imageTag:
    description: The unique tag name for the generated container
  deploymentRepo:
    description: The kustomize repository that the deployment should be comitted to
  rawBranchName:
    description: The raw branch name
  platforms:
    description: Sting. Comma-separated list of platforms to build the image for (to be passed to buildx)
  deployAzure:
    description: Bool. Whether to deploy to Azure on build
runs:
  using: "node20"
  main: "dist/index.js"
