name: 'e2g-setup-calculator-action'
description: 'Internal use'
author: 'Equity Engineering Group'
outputs:
  sum:
    description: 'The sum of the inputs'
runs:
  using: 'node16'
  main: 'dist/index.js'
