name: Rebuild Calculators
on:
  workflow_dispatch:
jobs:
  trigger:
    name: Trigger Rebuilds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [
          'api-1183-calculator',
          'asme-b31g-calculator',
          'bakeout-calculator',
          'bengi-worker-calculator',
          'best-rate-calculator',
          'bijlaard-calculator',
          'boiler-tube-calculator',
          'buried-pipelines-calculator',
          'branch-calculator',
          'bundle-sight-calculator',
          'burstp-calculator',
          'calculix-worker-calculator',
          'charpy-calculator',
          'circuit-corrosion-calculator',
          'corr-solutions-da-calculator',
          'corroding-pipe-life-calculator',
          'cp-design-calculator',
          'cp-design-offshore-calculator',
          'crack-attack-calculator',
          'lot-centered-analysis-calculator',
          'creep-life-calculator',
          'cui-calculator',
          'damage-sight-calculator',
          'deep-thought-calculator',
          'dent-fea-calculator',
          'exemption-calculator',
          'fast2-calculator',
          'fatigue-calculator',
          'fatigue-damage-calculator',
          'fatigue-data-explorer-calculator',
          'fea-visualization-calculator',
          'feature-identification-calculator',
          'ffs-brittle-calculator',
          'ffs-cracking-calculator',
          'ffs-creep-calculator',
          'ffs-dent-gouge-calculator',
          'ffs-fire-damage-calculator',
          'ffs-hydrogen-calculator',
          'ffs-laminations-calculator',
          'ffs-lta-calculator',
          'ffs-misalignment-calculator',
          'ffs-pitting-calculator',
          'ffs-thinning-calculator',
          'flange-calculator',
          'hottap-calculator',
          'htha-calculator',
          'htha-steady-state-calculator',
          'idinterp-calculator',
          'in-sight-calculator',
          'inspection-report-calculator',
          'insulation-calculator',
          'large-lta-calculator',
          'material-explorer-calculator',
          'mixer-calculator',
          'ncpv-nozzle-fea-calculator',
          'netica-worker-calculator',
          'nozzle-calculator',
          'nozzle-fea-calculator',
          'omega-calculator',
          'pipe-pt-calculator',
          'pipe-span-calculator',
          'plausible-profiles-calculator',
          'plume-calculator',
          'prd-update-calculator',
          'rainflow-calculator',
          'rbi-plus-calculator',
          'sage-x-calculator',
          'salome-worker-calculator',
          'sandman-calculator',
          'shell-pt-calculator',
          'shutdown-calculator',
          'simflex-calculator',
          'simflex-converters-calculator',
          'simflex-legacy-calculator',
          'smooth-bar-fatigue-life-calculator',
          'stored-energy-calculator',
          'tank-thickness-calculator',
          'tank-settlement-calculator',
          'tank-settlement-fea-calculator',
          'tank-sight-calculator',
          'tbreak-calculator',
          'thermowells-calculator',
          'toughness-calculator',
          'van-winkle-calculator',
          'welded-joint-fatigue-life-calculator',
        ]

    steps:
      - run: >
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.E2GBOT_PAT}}" \
            https://api.github.com/repos/e2grnd/${{ matrix.target_repo }}/dispatches \
            -d '{"event_type":"rebuild-calculator"}'

