name: Sync Files
on:
  push:
    branches:
      - main
    paths:
      - '.github/sync.yml'
      - '.github/workflows/sync.yml'
      - 'etc/repo-sync-config.yaml'
      - 'etc/rebuild_calculators/yaml'
  workflow_dispatch:
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.E2GBOT_PAT }}
          SKIP_PR: true
